on:
  push:
    branches: ["main"]
    
jobs:
  main:
    strategy:
      matrix:
        arch: [amd64,arm64]
        include:
          - arch: amd64
            runner_label: x86_64
          - arch: arm64
            runner_label: arm64

    runs-on: [self-hosted, ${{matrix.runner_label}}]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: buildx setup
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: soullessblob/ctf-bot:alpha
          platforms: linux/${{matrix.arch}}