on:
  push:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64,arm64]
        include:
          - arch: amd64
            runner_label: amd64
          - arch: arm64
            runner_label: arm64
    runs-on: 
      - ${{matrix.runner_label}}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: buildx setup
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ech00s/ctf-bot:alpha-${{matrix.arch}}
          platforms: linux/${{matrix.arch}}

  manifest:
    needs: build
    runs-on: 
      - self-hosted

    steps:
      - name: buildx setup
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: manifest
        run: docker buildx imagetools create -t ech00s/ctf-bot:alpha ech00s/ctf-bot:alpha-amd64 ech00s/ctf-bot:alpha-arm64
